## 1. Attending to different parts of the input with self-attention:
### 1.1 A simple self-attention mechansim without trainable weights:

In [3]:
import torch

inputs = torch.tensor(
    [[0.43, 0.15, 0.89], #your 
     [0.55, 0.87, 0.66], # journey 
     [0.57, 0.85, 0.64], #starts
     [0.22, 0.58, 0.33], #with 
     [0.77, 0.25, 0.10], #one
     [0.05, 0.80, 0.55]] #step
)

In [5]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [6]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [7]:
0.55*0.43 + 0.87*0.15 + 0.66*0.89

0.9544

In [8]:
torch.dot(input_query, input_1)

tensor(0.9544)

In [ ]:
for idx, ele in enumerate(inputs[0]):
    print(inputs[0][idx] * input_query[idx])


tensor(0.2365)
tensor(0.1305)
tensor(0.5874)


In [11]:
i = 2

res = torch.dot(inputs[i], input_query)
res


tensor(1.4754)

In [22]:
query = inputs[1] # 2nd input token is query

attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, input_query)

print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [13]:
attn_weights_2_tmp = attn_scores_2/attn_scores_2.sum()
attn_weights_2_tmp

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [14]:
attn_weights_2_tmp.sum()

tensor(1.0000)

In [15]:
def softmax_naive(x):
    return torch.exp(x) /torch.exp(x).sum(dim = 0)

softmax_naive(attn_scores_2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [16]:
torch.softmax(attn_scores_2, dim = 0)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [21]:
query = inputs[1] # 2nd input token is query

context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    print(f"{attn_scores_2[i]} -----> {inputs[i]}")
    context_vec_2 += attn_scores_2[i]*inputs[i]


print(context_vec_2)

0.9544000625610352 -----> tensor([0.4300, 0.1500, 0.8900])
1.4950001239776611 -----> tensor([0.5500, 0.8700, 0.6600])
1.4754000902175903 -----> tensor([0.5700, 0.8500, 0.6400])
0.8434000015258789 -----> tensor([0.2200, 0.5800, 0.3300])
0.7070000171661377 -----> tensor([0.7700, 0.2500, 0.1000])
1.0865000486373901 -----> tensor([0.0500, 0.8000, 0.5500])
tensor([2.8579, 4.2330, 3.7270])


### 1.2 A simple self attention mechanism without trainable weights:

In [24]:
attn_scores = torch.empty(6, 6)

for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)

print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [25]:
attn_scores = inputs @ inputs.T
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [26]:
attn_weights = torch.softmax(attn_scores, dim = 1)

In [27]:
attn_weights

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [28]:
attn_scores = inputs @ inputs.T
attn_weights = torch.softmax(attn_scores, dim = 1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [29]:
all_context_vecs = attn_weights @ inputs

all_context_vecs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

## 2.Implementing self-attention with trainable weights:
### 2.1 Computing the attention weights step by step:



In [37]:
x2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [41]:
x2

tensor([0.5500, 0.8700, 0.6600])

In [38]:
torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in, d_out))
W_key = torch.nn.Parameter(torch.rand(d_in, d_out))
W_value = torch.nn.Parameter(torch.rand(d_in, d_out))

In [40]:
query_2 = x2 @ W_query
query_2


tensor([0.4306, 1.4551], grad_fn=<SqueezeBackward4>)

In [ ]:
keys = inputs @ W_key
value = inputs @ W_value
keys.shape

torch.Size([6, 2])

In [45]:
keys

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]], grad_fn=<MmBackward0>)

In [46]:
keys_2 = keys[1]

attn_score_22 = torch.dot(query_2, keys_2)
attn_score_22

tensor(1.8524, grad_fn=<DotBackward0>)

In [47]:
attn_score_2 = query_2 @keys.T

In [48]:
attn_score_2

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
       grad_fn=<SqueezeBackward4>)

In [51]:
d_k = keys.shape[1]

attn_weights_2 = torch.softmax(attn_score_2/d_k ** 0.5, dim = -1)
attn_weights_2

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
       grad_fn=<SoftmaxBackward0>)

### 2. Implementing a compact self attention Class:

In [59]:
m = torch.nn.Linear(2, 3)
m.bias

Parameter containing:
tensor([0.1537, 0.1667, 0.2732], requires_grad=True)

In [61]:
import torch.nn as nn

class SelfAttention_v1(nn.Module):

    def __init__(self, d_in, d_out, qkv_bias = False):
        super().__init__()
        self.W_query = torch.nn.Linear(d_in, d_out, bias = qkv_bias )
        self.W_key = torch.nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_value = torch.nn.Linear(d_in, d_out, bias = qkv_bias)

    def forward(self, x):
        queries = self.W_query(inputs)
        keys = self.W_key(inputs)
        values = self.W_value(inputs)

        attn_scores =  queries @keys.T
        attn_weights = torch.softmax(attn_scores/d_k ** 0.5 , dim = 1)
        context_vec = attn_weights @ values
        return context_vec
    
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)

sa_v1(inputs)
    

tensor([[-0.5337, -0.1051],
        [-0.5323, -0.1080],
        [-0.5323, -0.1079],
        [-0.5297, -0.1076],
        [-0.5311, -0.1066],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)

## Hiding future words with causal attention 
#### 3. Applying a causal attention mask 

In [62]:
queries = sa_v1.W_query(inputs)
keys = sa_v1.W_key(inputs)
values = sa_v1.W_value(inputs)

attn_scores =  queries @keys.T
attn_weights = torch.softmax(attn_scores/d_k ** 0.5 , dim = 1)
context_vec = attn_weights @ values

In [63]:
attn_weights

tensor([[0.1717, 0.1762, 0.1761, 0.1555, 0.1627, 0.1579],
        [0.1636, 0.1749, 0.1746, 0.1612, 0.1605, 0.1652],
        [0.1637, 0.1749, 0.1746, 0.1611, 0.1606, 0.1651],
        [0.1636, 0.1704, 0.1702, 0.1652, 0.1632, 0.1674],
        [0.1667, 0.1722, 0.1721, 0.1618, 0.1633, 0.1639],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<SoftmaxBackward0>)

In [65]:
context_length = attn_scores.shape[0]
make_simple = torch.tril(torch.ones(context_length, context_length))
print(make_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [67]:
masked_simple = attn_weights * make_simple
masked_simple

tensor([[0.1717, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1636, 0.1749, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1637, 0.1749, 0.1746, 0.0000, 0.0000, 0.0000],
        [0.1636, 0.1704, 0.1702, 0.1652, 0.0000, 0.0000],
        [0.1667, 0.1722, 0.1721, 0.1618, 0.1633, 0.0000],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<MulBackward0>)

In [ ]:
row_sums = masked_simple.sum(dim = 1, keepdim = True)
masked_simple_norm = masked_simple /row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4833, 0.5167, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3190, 0.3408, 0.3402, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2545, 0.2542, 0.2468, 0.0000, 0.0000],
        [0.1994, 0.2060, 0.2058, 0.1935, 0.1953, 0.0000],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<DivBackward0>)


In [69]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal = 1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[0.3111,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.1655, 0.2602,   -inf,   -inf,   -inf,   -inf],
        [0.1667, 0.2602, 0.2577,   -inf,   -inf,   -inf],
        [0.0510, 0.1080, 0.1064, 0.0643,   -inf,   -inf],
        [0.1415, 0.1875, 0.1863, 0.0987, 0.1121,   -inf],
        [0.0476, 0.1192, 0.1171, 0.0731, 0.0477, 0.0966]],
       grad_fn=<MaskedFillBackward0>)


In [70]:
attn_weights = torch.softmax(masked/ d_k ** 0.5, dim = 1)
attn_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4833, 0.5167, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3190, 0.3408, 0.3402, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2545, 0.2542, 0.2468, 0.0000, 0.0000],
        [0.1994, 0.2060, 0.2058, 0.1935, 0.1953, 0.0000],
        [0.1624, 0.1709, 0.1706, 0.1654, 0.1625, 0.1682]],
       grad_fn=<SoftmaxBackward0>)

### 4. Masking additonal atttention weights with dropout:

In [71]:
torch.manual_seed(123)

layer = torch.nn.Dropout(0.5)


In [73]:
example = torch.ones(6, 6)
example

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [74]:
layer(example)

tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])

In [ ]:
dropout_rate = 0.5
1 / (1 - dropout_rate)

2.0

In [76]:
layer(attn_weights)

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6816, 0.6804, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5085, 0.4936, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.3906, 0.0000],
        [0.3249, 0.3418, 0.0000, 0.3308, 0.3249, 0.3363]],
       grad_fn=<MulBackward0>)

### 5. Implemention a compact causal self attention class:

In [78]:
batch = torch.stack((inputs, inputs), dim = 0)
batch.shape


torch.Size([2, 6, 3])

In [82]:
import torch.nn as nn

class causalAttention(nn.Module):

    def __init__(self, d_in, d_out, context_length, dropout,  qkv_bias = False):
        super().__init__()
        self.W_query = torch.nn.Linear(d_in, d_out, bias = qkv_bias )
        self.W_key = torch.nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_value = torch.nn.Linear(d_in, d_out, bias = qkv_bias)
        self.dropout = torch.nn.Dropout(dropout)
        self.register_buffer("mask", torch.triu(torch.ones(context_length, context_length), diagonal = 1))
    

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        queries = self.W_query(x)
        keys = self.W_key(x)
        values = self.W_value(x)

        attn_scores =  queries @keys.transpose(1, 2)
        attn_scores.masked_fill_(
            self.mask.bool()[:num_tokens, :num_tokens],-torch.inf
        )
        attn_weights = torch.softmax(attn_scores/keys.shape[-1] ** 0.5 , dim = -1)
        attn_weights = self.dropout(attn_weights)
        context_vec = attn_weights @ values
        return context_vec
    
torch.manual_seed(123)

context_length = batch.shape[1]
dropout = 0

ca  = causalAttention(d_in, d_out, context_length, dropout)

ca(batch)
    

tensor([[[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]],

        [[-0.4519,  0.2216],
         [-0.5874,  0.0058],
         [-0.6300, -0.0632],
         [-0.5675, -0.0843],
         [-0.5526, -0.0981],
         [-0.5299, -0.1081]]], grad_fn=<UnsafeViewBackward0>)

## Stacking multiple single head attention to multi-head attention:
### Stacking multiple single head attention layers

In [87]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self,d_in, d_out, context_length, dropout, num_heads = 2, qkv_bias = False):
        super().__init__()
        self.heads = nn.ModuleList(
        [causalAttention(d_in=d_in, d_out=d_out, context_length=context_length, dropout= dropout,qkv_bias = qkv_bias) for _ in range(num_heads)]
        )

    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim = -1)
    
torch.manual_seed(123)
context_length = batch.shape[1]
d_in, d_out = batch.shape[-1], 2

mha = MultiHeadAttentionWrapper(d_in, d_out, context_length, dropout = 0, num_heads = 2)
mha(batch)

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]],

        [[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]]], grad_fn=<CatBackward0>)

### Implementing Multi-head attention with weight splits:

In [88]:
import torch
import torch.nn as nn

class MultiHeadAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        assert d_out % num_heads == 0, "d_out must be divisible by num_heads"
        
        self.d_out = d_out
        self.num_heads = num_heads
        self.head_dim = d_out // num_heads  # per-head dimension

        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

        self.out_proj = nn.Linear(d_out, d_out)  # optional output projection
        self.dropout = nn.Dropout(dropout)

        # Register causal mask buffer (upper triangular with 1s above diagonal)
        mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
        self.register_buffer("mask", mask)

    def forward(self, x):
        """
        x: Tensor of shape (batch_size, context_length, d_in)
        Returns: Tensor of shape (batch_size, context_length, d_out)
        """
        b, num_tokens, _ = x.shape

        # Linear projections
        Q = self.W_query(x)  # (b, num_tokens, d_out)
        K = self.W_key(x)
        V = self.W_value(x)

        # Reshape to (b, num_heads, num_tokens, head_dim)
        Q = Q.view(b, num_tokens, self.num_heads, self.head_dim).transpose(1, 2)
        K = K.view(b, num_tokens, self.num_heads, self.head_dim).transpose(1, 2)
        V = V.view(b, num_tokens, self.num_heads, self.head_dim).transpose(1, 2)

        # Attention score: (b, num_heads, num_tokens, num_tokens)
        attn_scores = Q @ K.transpose(-2, -1)  # dot product

        # Apply causal mask
        mask = self.mask[:num_tokens, :num_tokens].bool()
        attn_scores = attn_scores.masked_fill(mask, float('-inf'))

        # Scale and normalize
        attn_weights = torch.softmax(attn_scores / (self.head_dim ** 0.5), dim=-1)
        attn_weights = self.dropout(attn_weights)

        # Attention output: (b, num_heads, num_tokens, head_dim)
        context = attn_weights @ V  # weighted sum

        # Reshape: (b, num_tokens, d_out)
        context = context.transpose(1, 2).contiguous().view(b, num_tokens, self.d_out)

        # Final linear projection
        output = self.out_proj(context)
        return output


In [89]:
# Input simulation
torch.manual_seed(123)
batch = torch.randn(4, 10, 8)  # (batch_size, context_length, d_in)

# Parameters
d_in = batch.shape[-1]
context_length = batch.shape[1]
d_out = 4
num_heads = 2

# Create MHA module
mha = MultiHeadAttention(d_in, d_out, context_length, dropout=0.0, num_heads=num_heads)

# Run forward pass
context_vecs = mha(batch)
print("Output shape:", context_vecs.shape)  # Should be: (4, 10, 4)


Output shape: torch.Size([4, 10, 4])


In [90]:
context_vecs

tensor([[[ 0.0520, -0.1580, -0.2882,  0.2626],
         [ 0.1114, -0.1909, -0.2495,  0.2917],
         [-0.0302, -0.0057, -0.1754,  0.0962],
         [ 0.2112, -0.2462, -0.0191,  0.2065],
         [ 0.0465,  0.0214, -0.3461,  0.1934],
         [ 0.0962, -0.0992, -0.2344,  0.2062],
         [ 0.0863,  0.0015, -0.1401,  0.0596],
         [ 0.2030, -0.1201, -0.0737,  0.1552],
         [ 0.1490, -0.1797, -0.0634,  0.1547],
         [ 0.1457, -0.1254, -0.0835,  0.1345]],

        [[ 0.5532, -0.5215,  0.3262,  0.3130],
         [ 0.3071, -0.2854, -0.1590,  0.3776],
         [-0.2297,  0.3996, -0.7485,  0.1439],
         [ 0.0079,  0.0374, -0.4983,  0.2279],
         [ 0.1145, -0.1690, -0.3022,  0.3187],
         [ 0.2782, -0.2588, -0.0776,  0.2403],
         [ 0.1554, -0.1560, -0.2491,  0.2946],
         [ 0.2021, -0.1919, -0.1572,  0.2800],
         [ 0.0692, -0.0603, -0.3228,  0.2750],
         [ 0.0367, -0.0455, -0.3605,  0.2521]],

        [[ 0.1159, -0.1009,  0.4081, -0.1870],
         